# Site settings
title:       Neat Tech 
email:       "sawyer@sawyeranderson.io"
author:      Sawyer Anderson
baseurl:     ''
description: "Pretty neat tech things!"
url:         "http://sawyercade.github.io"

# Build settings
markdown: kramdown
permalink: pretty
paginate: 3

# Google analytics
google_analytics:

# Optional features
animated:           false
show_related_posts: false
show_post_footers:  false
show_social_icons:  true

# Disqus post comments
# (leave blank to disable Disqus)
disqus_shortname:

# Social icons
github_username: sawyercade
stackoverflow_id:
twitter_username: sawyercade
google_plus_id:
linkedin_username: sawyer-anderson
angellist_username:
medium_id:
bitcoin_url:
paypal_url:
flattr_button:

# Post sharing icons
show_sharing_icons: true
share_text: 'Share this post!'
# Change to 'true' to enable individual icons
share_facebook: true
share_twitter: true
share_googleplus: false
share_linkedin: true
share_digg: false
share_tumblr: false
share_reddit: true
share_stumbleupon: false
share_hackernews: true

# Build settings
markdown:     kramdown
redcarpet:
  extensions: ['smart', 'tables', 'with_toc_data']
permalink:    pretty
paginate:     4
sass:
  compressed: true
gems:
  - jekyll-sitemap
